export const DICT = {
  SET_DICT_CODE: 'SET_DICT_CODE',
  SET_DICT_REQUEST_CACHE: 'SET_DICT_REQUEST_CACHE',
  RESET_DICT_REQUEST_CACHE_ITEM: 'RESET_DICT_REQUEST_CACHE_ITEM',
  DELETE_INVALID_DICT: 'DELETE_INVALID_DICT'
}



